apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: default
spec:
  serviceName: "mysql"  # Headless service for stable network identity
  replicas: 3          # Number of pods
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0   # MySQL Docker image
          ports:
            - containerPort: 3306
              name: mysql
          env:  # MySQL environment variables
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql  # Persistent storage location
  volumeClaimTemplates:  # Define PersistentVolumeClaims for each replica
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi   # Storage size per replica
        storageClassName: standard  # Replace with your StorageClass