---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-asg-jp-node-max
  namespace: monitoring
spec:
  concurrencyPolicy: Forbid
  schedule: '55 20 * * *'
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: sa-xxxxx
          restartPolicy: Never
          containers:
            - name: set-jp-asg-node-max
              image: xxxxxxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/cronjob-chg-asg:latest
              imagePullPolicy: Always
              env:
              - name: DESIRED_CAPACITY
                value: "16"
              - name: ASG_NAME
                value: "eksctl-demo-NodeGroup-DEQT18bKkWQ6"
              - name: REGION
                value: "ap-northeast-1"
              - name: SLACK_TOKEN
                value: "xoxb-xxxxxx"
              - name: SLACK_CHANNEL
                value: "#fox-xxxxx"
              - name: TEMPLATE_NAME
                value: "eksctl-xxxxxxxx"
              - name: TEMPLATE_VERSION
                value: "1"
              - name: MAX_NODE
                value: "17"
              - name: MINI_NODE
                value: "15"

